import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import chalk from 'chalk'
import type { DaemonExtensionTokenScope } from '@sepilotd/api-client'
import { DaemonClient, DEFAULT_DAEMON_BASE_URL } from '../client/http.js'
import { resolveDaemonBaseUrl } from '../client/token.js'
import { detectCliLocale } from '../utils/locale.js'

const EXTENSION_INSTALL_COPY = {
  en: {
    installedPrefix: (name: string) => `Extension installed: ${name}`,
    manifestPrefix: (path: string) => `  manifest: ${path}`,
    envFilePrefix: (path: string) => `  env file: ${path}`,
    tokenIdPrefix: (id: string) => `  token id: ${id}`,
    nextSteps: '\nNext steps:',
    tokenStoredNote: '\nThe generated token is stored in .sepilot/extension.env',
    invalidManifest: (path: string) => `Invalid extension manifest: ${path}`,
    unsupportedSchemaVersion: (path: string) => `Unsupported extension manifest schemaVersion in ${path}`,
    missingId: (path: string) => `Extension manifest is missing a valid id: ${path}`,
    missingName: (path: string) => `Extension manifest is missing a valid name: ${path}`,
    missingScopes: (path: string) => `Extension manifest is missing token.scopes: ${path}`,
    unsupportedScope: (scope: string, path: string) => `Unsupported extension manifest scope "${scope}" in ${path}`,
  },
  ko: {
    installedPrefix: (name: string) => `확장 설치됨: ${name}`,
    manifestPrefix: (path: string) => `  매니페스트: ${path}`,
    envFilePrefix: (path: string) => `  env 파일: ${path}`,
    tokenIdPrefix: (id: string) => `  토큰 ID: ${id}`,
    nextSteps: '\n다음 단계:',
    tokenStoredNote: '\n생성된 토큰은 .sepilot/extension.env에 저장됩니다',
    invalidManifest: (path: string) => `잘못된 확장 매니페스트: ${path}`,
    unsupportedSchemaVersion: (path: string) => `${path}에서 지원되지 않는 확장 매니페스트 schemaVersion`,
    missingId: (path: string) => `확장 매니페스트에 유효한 id가 없습니다: ${path}`,
    missingName: (path: string) => `확장 매니페스트에 유효한 name이 없습니다: ${path}`,
    missingScopes: (path: string) => `확장 매니페스트에 token.scopes가 없습니다: ${path}`,
    unsupportedScope: (scope: string, path: string) => `${path}에서 지원되지 않는 확장 매니페스트 scope "${scope}"`,
  },
} as const

function extensionInstallCopy() {
  return EXTENSION_INSTALL_COPY[detectCliLocale()] ?? EXTENSION_INSTALL_COPY.en
}

export interface ExtensionInstallOptions {
  url?: string
  expiresAt?: string
}

interface ExtensionManifest {
  schemaVersion: 1
  id: string
  name: string
  description?: string
  token: {
    scopes: DaemonExtensionTokenScope[]
  }
}

const ALLOWED_EXTENSION_TOKEN_SCOPES: readonly DaemonExtensionTokenScope[] = [
  'all',
  'inspect',
  'chat',
  'ws',
  'sessions',
  'memory',
  'files',
  'skills',
  'projects',
  'approvals',
  'extensions',
  'personas',
  'artifacts',
]

function isExtensionTokenScope(value: string): value is DaemonExtensionTokenScope {
  return ALLOWED_EXTENSION_TOKEN_SCOPES.includes(value as DaemonExtensionTokenScope)
}

const MANIFEST_FILE_NAME = 'sepilot.extension.json'
const MANAGED_ENV_RELATIVE_PATH = '.sepilot/extension.env'
const GITIGNORE_ENTRY = '.sepilot/'

export async function extensionInstallCommand(
  targetPath: string,
  options: ExtensionInstallOptions = {},
): Promise<void> {
  const copy = extensionInstallCopy()
  const install = await installExtensionManifest(targetPath, options)

  console.log(chalk.green(copy.installedPrefix(install.manifest.name)))
  console.log(chalk.gray(copy.manifestPrefix(install.manifestPath)))
  console.log(chalk.gray(copy.envFilePrefix(install.envFilePath)))
  console.log(chalk.gray(copy.tokenIdPrefix(install.tokenId)))
  console.log(chalk.gray(copy.nextSteps))
  console.log(chalk.cyan(`  cd ${install.extensionDir}`))
  console.log(chalk.cyan('  pnpm install'))
  console.log(chalk.cyan('  pnpm build'))
  console.log(chalk.cyan('  node dist/index.js help'))
  console.log(chalk.gray(copy.tokenStoredNote))
}

export async function installExtensionManifest(
  targetPath: string,
  options: ExtensionInstallOptions = {},
): Promise<{
  extensionDir: string
  manifestPath: string
  envFilePath: string
  manifest: ExtensionManifest
  tokenId: string
}> {
  const { extensionDir, manifestPath, manifest } = await loadExtensionManifest(
    targetPath,
  )
  const requestedScopes = parseManifestScopes(manifest.token.scopes, manifestPath)

  const client = new DaemonClient(options.url)
  const issued = await client.issueExtensionToken({
    label: manifest.name,
    scopes: requestedScopes,
    expiresAt: options.expiresAt,
  })

  const envFilePath = join(extensionDir, MANAGED_ENV_RELATIVE_PATH)
  await mkdir(dirname(envFilePath), { recursive: true })
  await writeFile(
    envFilePath,
    [
      '# Generated by `sepilot extension-install`.',
      `SEPILOT_DAEMON_URL=${resolveDaemonBaseUrl(options.url) ?? DEFAULT_DAEMON_BASE_URL}`,
      `SEPILOT_DAEMON_TOKEN=${issued.token}`,
      '',
    ].join('\n'),
    { mode: 0o600 },
  )
  await ensureGitignoreEntry(extensionDir, GITIGNORE_ENTRY)

  return {
    extensionDir,
    manifestPath,
    envFilePath,
    manifest,
    tokenId: issued.id,
  }
}

async function loadExtensionManifest(targetPath: string): Promise<{
  extensionDir: string
  manifestPath: string
  manifest: ExtensionManifest
}> {
  const resolvedTarget = resolve(targetPath)
  const manifestPath = resolvedTarget.endsWith('.json')
    ? resolvedTarget
    : join(resolvedTarget, MANIFEST_FILE_NAME)
  const extensionDir = dirname(manifestPath)
  const manifest = parseExtensionManifest(
    JSON.parse(await readFile(manifestPath, 'utf-8')),
    manifestPath,
  )

  return {
    extensionDir,
    manifestPath,
    manifest,
  }
}

function parseExtensionManifest(
  value: unknown,
  manifestPath: string,
): ExtensionManifest {
  const copy = extensionInstallCopy()
  if (
    typeof value !== 'object'
    || value === null
    || Array.isArray(value)
  ) {
    throw new Error(copy.invalidManifest(manifestPath))
  }

  const record = value as Record<string, unknown>
  if (record.schemaVersion !== 1) {
    throw new Error(copy.unsupportedSchemaVersion(manifestPath))
  }
  if (typeof record.id !== 'string' || record.id.trim() === '') {
    throw new Error(copy.missingId(manifestPath))
  }
  if (typeof record.name !== 'string' || record.name.trim() === '') {
    throw new Error(copy.missingName(manifestPath))
  }

  const token = record.token
  const tokenRecord = (
    typeof token === 'object'
    && token !== null
    && !Array.isArray(token)
  ) ? token as Record<string, unknown> : null
  if (
    !tokenRecord
    || !Array.isArray(tokenRecord.scopes)
  ) {
    throw new Error(copy.missingScopes(manifestPath))
  }

  const scopes = parseManifestScopes(tokenRecord.scopes, manifestPath)

  return {
    schemaVersion: 1,
    id: record.id.trim(),
    name: record.name.trim(),
    ...(typeof record.description === 'string' && record.description.trim()
      ? { description: record.description.trim() }
      : {}),
    token: {
      scopes,
    },
  }
}

function parseManifestScopes(
  value: unknown[],
  manifestPath: string,
): DaemonExtensionTokenScope[] {
  const copy = extensionInstallCopy()
  const normalizedScopes = value
    .map((scope) => (typeof scope === 'string' ? scope.trim() : ''))
    .filter((scope): scope is string => Boolean(scope))

  if (normalizedScopes.length === 0) {
    throw new Error(copy.missingScopes(manifestPath))
  }

  const scopes: DaemonExtensionTokenScope[] = []
  for (const scope of normalizedScopes) {
    if (!isExtensionTokenScope(scope)) {
      throw new Error(copy.unsupportedScope(scope, manifestPath))
    }
    scopes.push(scope)
  }

  return scopes
}

async function ensureGitignoreEntry(
  extensionDir: string,
  entry: string,
): Promise<void> {
  const gitignorePath = join(extensionDir, '.gitignore')

  let existing = ''
  try {
    existing = await readFile(gitignorePath, 'utf-8')
  } catch {
    // create below
  }

  const lines = existing.split(/\r?\n/)
  if (lines.includes(entry)) {
    return
  }

  const next = existing
    ? `${existing.replace(/\s*$/, '')}\n${entry}\n`
    : `${entry}\n`
  await writeFile(gitignorePath, next)
}
